INSERT INTO BRIGADE
(ID,BRIGADIER_ID,OPERATION_ID)
VALUES
(1, 11, 1)
/
INSERT INTO BRIGADE
(ID,BRIGADIER_ID,OPERATION_ID)
VALUES
(2, 13, 2)
/
INSERT INTO BRIGADE
(ID,BRIGADIER_ID,OPERATION_ID)
VALUES
(3, 15, 3)
/