CREATE TABLE WORKSHOP 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT WORKSHOP_NAME_NN NOT NULL,
	WORKSHOP_CHIEF_ID NUMBER(7)
	CONSTRAINT WORKSHOP_WORKSHOP_CHIEF_ID_NN NOT NULL
)


/
CREATE TABLE SECTOR 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT SECTOR_NAME_NN NOT NULL,
	SECTOR_CHIEF_ID NUMBER(7)
	CONSTRAINT SECTOR_SECTOR_CHIEF_ID_NN NOT NULL,
	MASTER_ID NUMBER(7)
	CONSTRAINT SECTOR_MASTER_ID_NN NOT NULL,
	WORKSHOP_ID NUMBER(7)
	CONSTRAINT SECTOR_WORKSHOP_ID_NN NOT NULL
)


/
CREATE TABLE PRODUCT 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT PRODUCT_NAME_NN NOT NULL,
	TYPE_ID NUMBER(7)
	CONSTRAINT PRODUCT_TYPE_ID_NN NOT NULL,
	ATTRIBUTE_ID NUMBER(7)
	CONSTRAINT PRODUCT_ATTRIBUTE_ID_NN NOT NULL
)


/
CREATE TABLE TEST 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT TEST_NAME_NN NOT NULL,
	TEST_PRODUCT_ID NUMBER(7)
	CONSTRAINT T_TEST_PRODUCT_ID_NN NOT NULL,
	START_DATE DATE
	CONSTRAINT TEST_START_DATE_NN NOT NULL,
	END_DATE DATE,
	TEST_TOOL VARCHAR2(20)
	CONSTRAINT TEST_TEST_TOOL_NN NOT NULL,
	TEST_LAB_ID NUMBER(7)
	CONSTRAINT TEST_TEST_LAB_ID_NN NOT NULL
)


/
CREATE TABLE PRODUCT_TYPE 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT PRODUCT_TYPE_NAME_NN NOT NULL,
	MODEL VARCHAR2(20)
	CONSTRAINT PRODUCT_TYPE_MODEL_NN NOT NULL,
	WORKSHOP_ID NUMBER(7)
	CONSTRAINT PRODUCT_TYPE_WORKSHOP_ID_NN NOT NULL
)


/
CREATE TABLE PRODUCT_ATTRIBUTE 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT PRODUCT_ATTRIBUTE_NAME_NN NOT NULL,
	VALUE VARCHAR2(20)
	CONSTRAINT PRODUCT_ATTRIBUTE_VALUE_NN NOT NULL
)


/
CREATE TABLE BRIGADE 
(
	ID NUMBER(7),
	BRIGADIER_ID NUMBER(7)
	CONSTRAINT BRIGADE_BRIGADIER_ID_NN NOT NULL,
	OPERATION_ID NUMBER(7)
	CONSTRAINT BRIGADE_OPERATION_ID_NN NOT NULL
)


/
CREATE TABLE SECTOR_OPERATION 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT SECTOR_OPERATION_NAME_NN NOT NULL,
	OP_PRODUCT_ID NUMBER(7)
	CONSTRAINT SECTOR_OP_OP_PRODUCT_ID_NN NOT NULL,
	START_DATE DATE
	CONSTRAINT SECTOR_OPERATION_START_DATE_NN NOT NULL,
	END_DATE DATE,
	SECTOR_ID NUMBER(7)
	CONSTRAINT SECTOR_OPERATION_SECTOR_ID_NN NOT NULL,
	BRIGADE_ID NUMBER(7)
	CONSTRAINT SECTOR_OPERATION_BRIGADE_ID_NN NOT NULL
)


/
CREATE TABLE WORKER 
(
	ID NUMBER(7),
	LAST_NAME VARCHAR2(20)
	CONSTRAINT WORKER_LAST_NAME_NN NOT NULL,
	FIRST_NAME VARCHAR2(20)
	CONSTRAINT WORKER_FIRST_NAMEE_NN NOT NULL,
	START_DATE DATE
	CONSTRAINT WORKER_START_DATE_NN NOT NULL,
	POSITION_ID NUMBER(7)
	CONSTRAINT WORKER_POSITION_ID_NN NOT NULL,
	BRIGADE_ID NUMBER(7),
	TEST_LAB_ID NUMBER(7)
)


/
CREATE TABLE POSITION 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT POSITION_NAME_NN NOT NULL,
	WORK_TYPE VARCHAR2(20)
	CONSTRAINT POSITION_WORK_TYPE_NN NOT NULL,
	ATTRIBUTE_ID NUMBER(7)
	CONSTRAINT POSITION_ATTRIBUTE_ID_NN NOT NULL
)


/
CREATE TABLE POSITION_ATTRIBUTE 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT POSITION_ATTRIBUTE_NAME_NN NOT NULL,
	VALUE VARCHAR2(20)
	CONSTRAINT POSITION_ATTRIBUTE_VALUE_NN NOT NULL
)


/
CREATE TABLE WORKSHOP_TESTLAB 
(
	WORKSHOP_ID NUMBER(7)
	CONSTRAINT W_T_WORKSHOP_ID_NN NOT NULL,
	TEST_LAB_ID NUMBER(7)
	CONSTRAINT W_T_TEST_LAB_ID_NN NOT NULL
)


/
CREATE TABLE WORKER_ATTRIBUTE 
(
	WORKER_ID NUMBER(7)
	CONSTRAINT W_A_WORKER_ID_NN NOT NULL,
	ATTRIBUTE_ID NUMBER(7)
	CONSTRAINT W_A_ATTRIBUTE_ID_NN NOT NULL
)


/
CREATE TABLE TEST_LAB 
(
	ID NUMBER(7),
	NAME VARCHAR2(20)
	CONSTRAINT TEST_LAB_NAME_NN NOT NULL
)


