DROP TABLE WORKSHOP CASCADE CONSTRAINTS;
/
DROP TABLE SECTOR CASCADE CONSTRAINTS;
/
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
/
DROP TABLE TEST CASCADE CONSTRAINTS;
/
DROP TABLE PRODUCT_TYPE CASCADE CONSTRAINTS;
/
DROP TABLE PRODUCT_ATTRIBUTE CASCADE CONSTRAINTS;
/
DROP TABLE BRIGADE CASCADE CONSTRAINTS;
/
DROP TABLE SECTOR_OPERATION CASCADE CONSTRAINTS;
/
DROP TABLE WORKER CASCADE CONSTRAINTS;
/
DROP TABLE POSITION CASCADE CONSTRAINTS;
/
DROP TABLE POSITION_ATTRIBUTE CASCADE CONSTRAINTS;
/
DROP TABLE WORKSHOP_TESTLAB CASCADE CONSTRAINTS;
/
DROP TABLE WORKER_ATTRIBUTE CASCADE CONSTRAINTS;
/
DROP TABLE TEST_LAB CASCADE CONSTRAINTS;
/
