INSERT INTO POSITION 
(ID,NAME,WORK_TYPE,ATTRIBUTE_ID)
VALUES
(1, 'ENGINEER', 'TECH', 1)
/
INSERT INTO POSITION 
(ID,NAME,WORK_TYPE,ATTRIBUTE_ID)
VALUES
(2, 'TECHNOLOGIST', 'TECH', 2)
/
INSERT INTO POSITION 
(ID,NAME,WORK_TYPE,ATTRIBUTE_ID)
VALUES
(3, 'TECHNICAN', 'TECH', 3)
/
INSERT INTO POSITION 
(ID,NAME,WORK_TYPE,ATTRIBUTE_ID)
VALUES
(4, 'WELDER', 'LABOR', 4)
/
INSERT INTO POSITION 
(ID,NAME,WORK_TYPE,ATTRIBUTE_ID)
VALUES
(5, 'ASSEMBLER', 'LABOR', 5)
/
INSERT INTO POSITION 
(ID,NAME,WORK_TYPE,ATTRIBUTE_ID)
VALUES
(6, 'PAINTER', 'LABOR', 6)
/
INSERT INTO POSITION 
(ID,NAME,WORK_TYPE,ATTRIBUTE_ID)
VALUES
(7, 'TESTER', 'TESTER', 7)
/