INSERT INTO POSITION_ATTRIBUTE 
(ID,NAME,VALUE)
VALUES
(1, 'EXPERIENCE', '5')
/
INSERT INTO POSITION_ATTRIBUTE 
(ID,NAME,VALUE)
VALUES
(2, 'RATING', '4')
/
INSERT INTO POSITION_ATTRIBUTE 
(ID,NAME,VALUE)
VALUES
(3, 'GRADE', '2')
/
INSERT INTO POSITION_ATTRIBUTE 
(ID,NAME,VALUE)
VALUES
(4, 'POWER', '7')
/
INSERT INTO POSITION_ATTRIBUTE 
(ID,NAME,VALUE)
VALUES
(5, 'CLEVER', '78')
/
INSERT INTO POSITION_ATTRIBUTE 
(ID,NAME,VALUE)
VALUES
(6, 'KARMA', '99')
/
INSERT INTO POSITION_ATTRIBUTE 
(ID,NAME,VALUE)
VALUES
(7, 'TESTINGLVL', '80')
/