INSERT INTO PRODUCT_ATTRIBUTE 
(ID, NAME, VALUE)
VALUES
(1, 'FUEL CONSUMPTION', '10')
/
INSERT INTO PRODUCT_ATTRIBUTE 
(ID, NAME, VALUE)
VALUES
(2, 'FUEL CONSUMPTION', '15')
/
INSERT INTO PRODUCT_ATTRIBUTE 
(ID, NAME, VALUE)
VALUES
(3, 'CAPACITY', '26')
/
INSERT INTO PRODUCT_ATTRIBUTE 
(ID, NAME, VALUE)
VALUES
(4, 'ROOMINESS', '20')
/
INSERT INTO PRODUCT_ATTRIBUTE 
(ID, NAME, VALUE)
VALUES
(5, 'POWER', '400')
/
INSERT INTO PRODUCT_ATTRIBUTE 
(ID, NAME, VALUE)
VALUES
(6, 'MAX SPEED', '300')
/