INSERT INTO PRODUCT 
(ID,NAME,TYPE_ID,ATTRIBUTE_ID)
VALUES
(1, 'Nissan Qashqai', 1, 1)
/
INSERT INTO PRODUCT 
(ID,NAME,TYPE_ID,ATTRIBUTE_ID)
VALUES
(2, 'Ford Fusion', 2, 2)
/
INSERT INTO PRODUCT 
(ID,NAME,TYPE_ID,ATTRIBUTE_ID)
VALUES
(3, 'MAZ-5278', 3, 3)
/
INSERT INTO PRODUCT 
(ID,NAME,TYPE_ID,ATTRIBUTE_ID)
VALUES
(4, 'PAZ-678M', 4, 4)
/
INSERT INTO PRODUCT 
(ID,NAME,TYPE_ID,ATTRIBUTE_ID)
VALUES
(5, 'BELARUS-MT', 5, 5)
/
INSERT INTO PRODUCT 
(ID,NAME,TYPE_ID,ATTRIBUTE_ID)
VALUES
(6, 'SUZUKI-FLTR', 6, 6)
/
