INSERT INTO PRODUCT_TYPE 
(ID,NAME,MODEL,WORKSHOP_ID)
VALUES
(1, 'CAR', 'CROSSOVER', 1)
/
INSERT INTO PRODUCT_TYPE 
(ID,NAME,MODEL,WORKSHOP_ID)
VALUES
(2, 'CAR', 'SEDAN', 1)
/
INSERT INTO PRODUCT_TYPE 
(ID,NAME,MODEL,WORKSHOP_ID)
VALUES
(3, 'TRUCK', 'GOODS', 1)
/
INSERT INTO PRODUCT_TYPE 
(ID,NAME,MODEL,WORKSHOP_ID)
VALUES
(4, 'BUS', 'LITTLE', 1)
/
INSERT INTO PRODUCT_TYPE 
(ID,NAME,MODEL,WORKSHOP_ID)
VALUES
(5, 'TRACTOR', 'FIELD', 2)
/
INSERT INTO PRODUCT_TYPE 
(ID,NAME,MODEL,WORKSHOP_ID)
VALUES
(6, 'MOTO', 'SPEED', 2)
/