INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,END_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(1,'PAINTING',1,TO_DATE('21.04.2014','dd.mm.yyyy'),TO_DATE('23.07.2014','dd.mm.yyyy'),1,1)
/
INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,END_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(2,'WELDING',1,TO_DATE('24.07.2014','dd.mm.yyyy'),TO_DATE('05.08.2014','dd.mm.yyyy'),2,2)
/
INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(3,'ASSEMBLY',1,TO_DATE('10.08.2014','dd.mm.yyyy'),3,3)
/
INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,END_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(4,'PAINTING',2,TO_DATE('01.01.2014','dd.mm.yyyy'),TO_DATE('25.02.2014','dd.mm.yyyy'),1,1)
/
INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,END_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(5,'WELDING',3,TO_DATE('05.04.2014','dd.mm.yyyy'),TO_DATE('25.06.2014','dd.mm.yyyy'),2,2)
/
INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,END_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(6,'ASSEMBLY',4,TO_DATE('09.11.2014','dd.mm.yyyy'),TO_DATE('25.02.2015','dd.mm.yyyy'),3,3)
/
INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,END_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(7,'ASSEMBLY',5,TO_DATE('09.03.2015','dd.mm.yyyy'),TO_DATE('13.03.2015','dd.mm.yyyy'),3,3)
/
INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,END_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(8,'WELDING',6,TO_DATE('05.04.2015','dd.mm.yyyy'),TO_DATE('25.06.2015','dd.mm.yyyy'),2,2)
/
INSERT INTO SECTOR_OPERATION 
(ID,NAME,OP_PRODUCT_ID,START_DATE,SECTOR_ID,BRIGADE_ID)
VALUES
(9,'ASSEMBLY',6,TO_DATE('26.06.2015','dd.mm.yyyy'),3,3)
/