INSERT INTO SECTOR 
(ID,NAME,SECTOR_CHIEF_ID,MASTER_ID,WORKSHOP_ID)
VALUES
(1, 'SECTOR1', 3, 6, 1)
/
INSERT INTO SECTOR 
(ID,NAME,SECTOR_CHIEF_ID,MASTER_ID,WORKSHOP_ID)
VALUES
(2, 'SECTOR2', 4, 8, 2)
/
INSERT INTO SECTOR 
(ID,NAME,SECTOR_CHIEF_ID,MASTER_ID,WORKSHOP_ID)
VALUES
(3, 'SECTOR3', 5, 9, 2)
/

