INSERT INTO TEST 
(ID,NAME,TEST_PRODUCT_ID,START_DATE,END_DATE,TEST_TOOL,TEST_LAB_ID)
VALUES
(1, 'STRENGTH', 1, TO_DATE('24.07.2014','dd.mm.yyyy'), TO_DATE('25.07.2014','dd.mm.yyyy'), 'TOOL1', 1)
/
INSERT INTO TEST 
(ID,NAME,TEST_PRODUCT_ID,START_DATE,END_DATE,TEST_TOOL,TEST_LAB_ID)
VALUES
(2, 'QUALITY', 2, TO_DATE('27.07.2014','dd.mm.yyyy'), TO_DATE('29.07.2014','dd.mm.yyyy'), 'TOOL2', 1)
/
INSERT INTO TEST 
(ID,NAME,TEST_PRODUCT_ID,START_DATE,TEST_TOOL,TEST_LAB_ID)
VALUES
(3, 'EFFICIENCY', 3, TO_DATE('24.04.2015','dd.mm.yyyy'), 'TOOL3', 2)
/
INSERT INTO TEST 
(ID,NAME,TEST_PRODUCT_ID,START_DATE,END_DATE,TEST_TOOL,TEST_LAB_ID)
VALUES
(4, 'STRENGTH', 4, TO_DATE('28.11.2014','dd.mm.yyyy'), TO_DATE('24.02.2015','dd.mm.yyyy'), 'TOOL1', 1)
/
INSERT INTO TEST 
(ID,NAME,TEST_PRODUCT_ID,START_DATE,TEST_TOOL,TEST_LAB_ID)
VALUES
(5, 'QUALITY', 5, TO_DATE('04.12.2015','dd.mm.yyyy'), 'TOOL2', 1)
/
INSERT INTO TEST 
(ID,NAME,TEST_PRODUCT_ID,START_DATE,END_DATE,TEST_TOOL,TEST_LAB_ID)
VALUES
(6, 'EFFICIENCY', 6, TO_DATE('27.08.2015','dd.mm.yyyy'), TO_DATE('29.08.2015','dd.mm.yyyy'),  'TOOL3', 2)
/
INSERT INTO TEST 
(ID,NAME,TEST_PRODUCT_ID,START_DATE,END_DATE,TEST_TOOL,TEST_LAB_ID)
VALUES
(7, 'EFFICIENCY', 5, TO_DATE('01.09.2015','dd.mm.yyyy'), TO_DATE('20.09.2015','dd.mm.yyyy'),  'TOOL3', 2)
/
INSERT INTO TEST 
(ID,NAME,TEST_PRODUCT_ID,START_DATE,TEST_TOOL,TEST_LAB_ID)
VALUES
(8, 'EFFICIENCY', 4, TO_DATE('24.09.2015','dd.mm.yyyy'),  'TOOL3', 2)
/