INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(1,'Homer', 'Simpson', TO_DATE('23.05.1996','dd.mm.yyyy'), 1)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(2,'Ned', 'Flanders', TO_DATE('21.03.1999','dd.mm.yyyy'), 2)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(3,'Kent', 'Brockman', TO_DATE('14.02.2001','dd.mm.yyyy'), 3)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(4,'Barney', 'Gumble', TO_DATE('23.08.1998','dd.mm.yyyy'), 1)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(5,'Cletus', 'Spuckler', TO_DATE('06.05.2003','dd.mm.yyyy'), 2)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(6,'Moe', 'Szyslak', TO_DATE('03.12.2005','dd.mm.yyyy'), 3)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(7,'Ralph', 'Wiggum', TO_DATE('01.01.2015','dd.mm.yyyy'), 1)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(8,'Montgomery', 'Burns', TO_DATE('14.01.2012','dd.mm.yyyy'), 2)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(9,'Selma', 'Bouvier', TO_DATE('12.12.2012','dd.mm.yyyy'), 3)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID)
VALUES
(10,'Jasper', 'Beardly', TO_DATE('08.11.2001','dd.mm.yyyy'), 1)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,BRIGADE_ID)
VALUES
(11,'Aristotle', 'Amadopolis', TO_DATE('28.11.2011','dd.mm.yyyy'), 4, 1)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,BRIGADE_ID)
VALUES
(12,'Edna', 'Krabappel', TO_DATE('04.06.2010','dd.mm.yyyy'), 5, 1)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,BRIGADE_ID)
VALUES
(13,'Dan', 'Castellaneta', TO_DATE('07.11.2001','dd.mm.yyyy'), 6, 2)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,BRIGADE_ID)
VALUES
(14,'Lenny', 'Leonard', TO_DATE('08.01.2009','dd.mm.yyyy'), 4, 2)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,BRIGADE_ID)
VALUES
(15,'Otto', 'Mann', TO_DATE('03.05.2002','dd.mm.yyyy'), 5, 3)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,BRIGADE_ID)
VALUES
(16,'Martin', 'Prince', TO_DATE('05.09.2001','dd.mm.yyyy'), 6, 3)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,TEST_LAB_ID)
VALUES
(17,'Sideshow', 'Bob', TO_DATE('12.04.2006','dd.mm.yyyy'), 7, 1)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,TEST_LAB_ID)
VALUES
(18,'Waylon', 'Smithers', TO_DATE('18.11.2007','dd.mm.yyyy'), 7, 2)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,TEST_LAB_ID)
VALUES
(19,'Hank', 'Azaria', TO_DATE('12.11.2012','dd.mm.yyyy'), 7, 2)
/
INSERT INTO WORKER
(ID,FIRST_NAME,LAST_NAME,START_DATE,POSITION_ID,TEST_LAB_ID)
VALUES
(20,'Snake', 'Jailbird', TO_DATE('08.01.2000','dd.mm.yyyy'), 7, 1)
