INSERT INTO WORKSHOP_TESTLAB 
(WORKSHOP_ID,TEST_LAB_ID)
VALUES
(1, 1)
/
INSERT INTO WORKSHOP_TESTLAB 
(WORKSHOP_ID,TEST_LAB_ID)
VALUES
(1, 2)
/
INSERT INTO WORKSHOP_TESTLAB 
(WORKSHOP_ID,TEST_LAB_ID)
VALUES
(2, 2)
/