INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(1, 1)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(2, 2)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(3, 3)
/INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(4, 1)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(5, 2)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(6, 3)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(7, 1)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(8, 2)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(9, 3)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(10, 1)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(11, 4)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(12, 5)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(13, 6)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(14, 4)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(15, 5)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(16, 6)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(17, 7)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(18, 7)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(19, 7)
/
INSERT INTO WORKER_ATTRIBUTE 
(WORKER_ID,ATTRIBUTE_ID)
VALUES
(20, 7)
/
