SELECT S_REGION.NAME, COUNT(S_CUSTOMER.ID)
FROM S_REGION, S_CUSTOMER
WHERE S_CUSTOMER.REGION_ID=S_REGION.ID
GROUP BY S_REGION.NAME;

SELECT S_CUSTOMER.NAME, S_ORD.ID, S_ORD.TOTAL
FROM S_CUSTOMER, S_ORD
WHERE S_ORD.CUSTOMER_ID(+)=S_CUSTOMER.ID;

SELECT S_CUSTOMER.NAME, S_PRODUCT.NAME, S_ITEM.QUANTITY, S_ITEM.PRICE*S_ITEM.QUANTITY
FROM S_CUSTOMER, S_PRODUCT, S_ITEM, S_ORD
WHERE S_ITEM.PRODUCT_ID=S_PRODUCT.ID
AND S_ORD.CUSTOMER_ID=S_CUSTOMER.ID
AND S_ITEM.ORD_ID=S_ORD.ID
ORDER BY S_CUSTOMER.NAME;