SELECT DEPT_ID, COUNT(*) "Quantity of workers"
FROM S_EMP
GROUP BY DEPT_ID;

SELECT SALES_REP_ID, COUNT(*)
FROM S_CUSTOMER
GROUP BY SALES_REP_ID;

SELECT TO_CHAR(START_DATE, 'yyyy') Year, COUNT(ID) Employees
FROM S_EMP
GROUP BY TO_CHAR(START_DATE, 'yyyy');