
SELECT LAST_NAME, FIRST_NAME
FROM S_EMP
WHERE FIRST_NAME LIKE '________%'
ORDER BY SALARY DESC;

SELECT ID, NAME, NVL(IMAGE_ID, 'NO IMAGE') 
FROM S_PRODUCT;

SELECT TO_CHAR(SYSDATE-1, 'DAY') "Previous day"
FROM DUAL
WHERE NEXT_DAY(SYSDATE, 'FRIDAY')-SYSDATE=7;