ALTER TABLE S_EMP
ADD CONSTRAINT S_EMP_id_pk PRIMARY KEY(ID);

CREATE TABLE S_EMP_ADRES
(ID NUMBER(7)
CONSTRAINT TABLE S_EMP_ADRES_id_pk PRIMARY KEY,
COUNTRY VARCHAR2(128),
TOWN VARCHAR2(128)
CONSTRAINT S_EMP_ADRES_town_nn NOT NULL,
ADRESS VARCHAR2(300)
CONSTRAINT S_EMP_ADRES_adress_nn NOT NULL,
S_EMP_ID NUMBER(7)
CONSTRAINT S_EMP_ADRES_S_EMP_ID_nn NOT NULL
CONSTRAINT S_EMP_ADRES_S_EMP_ID_fk REFERENCES S_EMP(ID));

SELECT constraint_name, constraint_type, search_condition, r_constraint_name
FROM user_constraints
WHERE table_name = 'S_EMP_ADRES';

CREATE SEQUENCE S_EMP_ADRES_ID
INCREMENT BY 1
START BY 0
MAXVALUE 5
NOCACHE
NOCYCLE;

ALTER TABLE S_EMP_ADRES
DROP PRIMARY KEY CASCADE;

TRUNCATE S_EMP_ADRES;

DROP TABLE S_EMP_ADRES;