CREATE VIEW PROD_NOT_92(name)
AS SELECT S_PRODUCT.NAME 
FROM S_PRODUCT, S_ITEM, S_ORD
WHERE S_ITEM.PRODUCT_ID=S_PRODUCT.ID
AND S_ITEM.ORD_ID=S_ORD.ID
AND TO_CHAR(S_ORD.DATE_ORDERED, 'yyyy') NOT LIKE '1992';

DROP VIEW PROD_NOT_92; 

CREATE VIEW CUST_PROD_PRICE(NAME, PRODUCT, QUANTITY, PRICE)
AS SELECT S_CUSTOMER.NAME, S_PRODUCT.NAME, COUNT(S_PRODUCT.NAME), SUM(S_ITEM.PRICE)
FROM S_CUSTOMER, S_PRODUCT, S_ITEM, S_ORD
WHERE REGION_ID=1
AND S_ORD.CUSTOMER_ID=S_CUSTOMER.ID
AND S_ITEM.ORD_ID=S_ORD.ID
AND S_ITEM.PRODUCT_ID=S_PRODUCT.ID
GROUP BY S_CUSTOMER.NAME, S_PRODUCT.NAME;

DROP VIEW CUST_PROD_PRICE; 