/*2 вариант*/

SELECT NAME, CREDIT_RATING
FROM S_CUSTOMER
WHERE REGION_ID IN
(SELECT REGION_ID
FROM S_CUSTOMER
WHERE LOWER(NAME) LIKE '%w%s%');


SELECT S_CUSTOMER.NAME, S_REGION.NAME
FROM S_CUSTOMER, S_REGION
WHERE S_CUSTOMER.REGION_ID=S_REGION.ID
AND S_CUSTOMER.ID IN
(SELECT CUSTOMER_ID
FROM S_ORD
WHERE TOTAL > 
(SELECT AVG(SUM(TOTAL)) FROM S_ORD GROUP BY CUSTOMER_ID));


SELECT S_DEPT.NAME, S_EMP.LAST_NAME, S_EMP.FIRST_NAME, COUNT(*)
FROM S_DEPT, S_EMP, S_ORD
WHERE S_EMP.DEPT_ID=S_DEPT.ID
AND S_ORD.SALES_REP_ID=S_EMP.ID
AND S_DEPT.REGION_ID IN
(SELECT REGION_ID
FROM S_CUSTOMER
WHERE CREDIT_RATING LIKE 'EXCELLENT')
GROUP BY S_DEPT.NAME, S_EMP.LAST_NAME, S_EMP.FIRST_NAME;


SELECT S_EMP.LAST_NAME, S_EMP.FIRST_NAME, COUNT(*)
FROM S_DEPT, S_EMP, S_ORD
WHERE S_EMP.DEPT_ID=S_DEPT.ID
AND S_ORD.SALES_REP_ID=S_EMP.ID
AND S_EMP.DEPT_ID IN 
(SELECT DEPT_ID
FROM S_EMP
HAVING COUNT(*) = 
(SELECT MAX(COUNT(*))
FROM S_EMP
GROUP BY DEPT_ID)
GROUP BY DEPT_ID)
GROUP BY S_EMP.LAST_NAME, S_EMP.FIRST_NAME;