ALTER TABLE s_emp
DROP CONSTRAINT s_emp_comission_pct_ck;
/
CREATE TABLE ZAKAZ_D
(ID NUMBER,
ORDER_ID NUMBER,
PRODUCT_ID NUMBER,
QUANTITY NUMBER,
COMMENTS VARCHAR2(20));
/
CREATE SEQUENCE ZAKAZ_SEQ_D
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 20;
/
CREATE TABLE STAG_D
(ID NUMBER,
EMP_ID NUMBER,
LAST_NAME VARCHAR2(100),
FIRST_NAME VARCHAR2(100),
START_DATE DATE,
COMMENTS VARCHAR2(100));
/
CREATE SEQUENCE STAG_SEQ_D
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOCACHE;
/
-- LAB2 specification
CREATE OR REPLACE PACKAGE LAB2 IS

  PROCEDURE SET_COMM(EMP_ID IN NUMBER);

  PROCEDURE CUST_UPDATE;

  FUNCTION WY_COUNT(EMP_ID IN NUMBER, FLAG NUMBER) RETURN NUMBER;

  PROCEDURE ZAKAZ_P;

  PROCEDURE WEXPERIENCE;

END LAB2;
/
CREATE OR REPLACE PACKAGE BODY LAB2 IS
-- 1
PROCEDURE SET_COMM (EMP_ID IN NUMBER)
AS
ORD_SUM NUMBER;
NEW_COMM NUMBER;
BEGIN

  SELECT SUM(TOTAL)
    INTO ORD_SUM
    FROM S_ORD
    WHERE SALES_REP_ID = EMP_ID;

  DBMS_OUTPUT.PUT_LINE(ORD_SUM);

  IF ORD_SUM < 10000
  THEN
    NEW_COMM := 10;
  ELSIF ORD_SUM > 10000
    AND ORD_SUM < 1000000
  THEN
    NEW_COMM := 15;
  ELSIF ORD_SUM IS NULL
  THEN
    NEW_COMM := 0;
  END IF;

  UPDATE S_EMP
    SET COMMISSION_PCT = NEW_COMM
    WHERE ID = EMP_ID;

END SET_COMM;


--2
PROCEDURE CUST_UPDATE 
AS
  REGION_NUM NUMBER;
  UPD_LINE NUMBER;
BEGIN
  REGION_NUM := 1;
  UPD_LINE := 0;

SAVEPOINT SP;

LOOP
  SELECT COUNT(ID)
    INTO UPD_LINE
    FROM S_CUSTOMER
    WHERE REGION_ID = REGION_NUM;

  IF MOD(REGION_NUM, 2) = 0
  THEN
    UPDATE S_CUSTOMER
      SET CREDIT_RATING = 'EXCELLENT';
  ELSE
    UPDATE S_CUSTOMER
      SET CREDIT_RATING = 'GOOD';
  END IF;
  REGION_NUM := REGION_NUM + 1;
  EXIT WHEN REGION_NUM > 6;

  IF (UPD_LINE < 3)
  THEN
    DBMS_OUTPUT.PUT_LINE('Fewer then 3 customer records updated for region number ' || REGION_NUM);
  ELSE
    DBMS_OUTPUT.PUT_LINE(UPD_LINE || ' rows updated for region number ' || REGION_NUM);
  END IF;
END LOOP;

ROLLBACK TO SP;
END CUST_UPDATE;


--3
PROCEDURE ZAKAZ_P 
AS
  TMP_COMMENTS VARCHAR2(20);
  TMP_ID NUMBER := 1;
  UPD NUMBER := 0;
  SEQCUR NUMBER;
BEGIN

INSERT INTO ZAKAZ_D(ID, ORDER_ID, PRODUCT_ID, QUANTITY, COMMENTS)
SELECT ZAKAZ_SEQ_D.NEXTVAL, S_ORD.ID, S_PRODUCT.ID, S_ITEM.QUANTITY_SHIPPED, S_REGION.NAME
FROM S_ORD, S_ITEM, S_PRODUCT, S_CUSTOMER, S_REGION
WHERE S_ITEM.ORD_ID=S_ORD.ID
AND S_ITEM.PRODUCT_ID=S_PRODUCT.ID
AND S_ORD.CUSTOMER_ID=S_CUSTOMER.ID
AND S_CUSTOMER.REGION_ID=S_REGION.ID
AND S_ORD.TOTAL > 50000;

SELECT ZAKAZ_SEQ_D.CURRVAL INTO SEQCUR FROM DUAL;

WHILE TMP_ID <= SEQCUR LOOP
  SELECT COMMENTS
  INTO TMP_COMMENTS
  FROM ZAKAZ_D
  WHERE ID=TMP_ID;
    IF (LOWER(TMP_COMMENTS) NOT LIKE 'europe') THEN
      UPDATE ZAKAZ_D 
      SET COMMENTS = 'out region'
      WHERE ID=TMP_ID;
      UPD:=UPD+1;
    END IF;
  TMP_ID:=TMP_ID+1;
END LOOP;

IF (UPD=SEQCUR) THEN
  DBMS_OUTPUT.PUT_LINE('No customers from Europe');
END IF;
END ZAKAZ_P;


--4
FUNCTION WY_COUNT (EMP_ID IN NUMBER, FLAG NUMBER)
  RETURN NUMBER
AS
  WY NUMBER;
  TENY DATE;
  OVERTENY NUMBER := 0;
BEGIN

IF (FLAG = 0) THEN
SELECT TO_NUMBER(trunc(months_between(SYSDATE, start_date)/12))
INTO WY
FROM S_EMP
WHERE S_EMP.ID=EMP_ID;
RETURN WY;
END IF;

IF (FLAG = 1) THEN
SELECT ADD_MONTHS(start_date, 120)
INTO TENY
FROM S_EMP
WHERE S_EMP.ID=EMP_ID;
RETURN TO_NUMBER(TO_CHAR(TENY, 'YYYY'));
END IF;
END WY_COUNT;


--5
PROCEDURE WEXPERIENCE 
AS
  TEMP_ID NUMBER := 1;
  WY NUMBER := 0;
  OVERTENY NUMBER := 0;
  ISJUBILEE NUMBER := 0;
  TMP_NAME VARCHAR2(20);
  SEQCUR NUMBER;
BEGIN

INSERT INTO STAG_D(ID, EMP_ID, LAST_NAME, FIRST_NAME, START_DATE)
SELECT STAG_SEQ_D.NEXTVAL, S_EMP.ID, S_EMP.LAST_NAME, S_EMP.FIRST_NAME, S_EMP.START_DATE
FROM S_EMP;

SELECT ZAKAZ_SEQ_D.CURRVAL INTO SEQCUR FROM DUAL;

WHILE TEMP_ID <= SEQCUR LOOP
  IF (MOD(TEMP_ID, 2)=0) THEN
    UPDATE STAG_D
    SET COMMENTS = 'Work expirience - '||LAB2.WY_COUNT(TEMP_ID, 0)||' years'
    WHERE ID=TEMP_ID;
  ELSE
    UPDATE STAG_D
    SET COMMENTS = '10 year of work in - '||LAB2.WY_COUNT(TEMP_ID, 1)||' year'
    WHERE ID=TEMP_ID;
  END IF;

  SELECT LAB2.WY_COUNT(TEMP_ID, 0)
  INTO WY
  FROM DUAL;
  IF (WY>10) THEN
    OVERTENY:=OVERTENY+1;
  END IF;

  SELECT LAB2.WY_COUNT(TEMP_ID, 1)
  INTO ISJUBILEE
  FROM DUAL;
  IF (ISJUBILEE = EXTRACT(YEAR FROM SYSDATE)) THEN
    SELECT FIRST_NAME
    INTO TMP_NAME
    FROM STAG_D
    WHERE ID = TEMP_ID;
    DBMS_OUTPUT.PUT_LINE('Congratulations '||TMP_NAME||' 10 anniversary work');
  END IF;

  TEMP_ID:=TEMP_ID+1;
END LOOP;

DBMS_OUTPUT.PUT_LINE(OVERTENY||' workers have expirience over 10 year');
END WEXPERIENCE;

END LAB2;
/